import type { FirebaseOptions } from 'firebase/app';

// This is your web app's Firebase configuration.
// It was automatically generated by Firebase Studio.
export const firebaseConfig: FirebaseOptions = {
    apiKey: "AIzaSyACh5lFhU9BWtWEa6l4WVTtSS1VJcuzn90",
    authDomain: "studio-2419555289-92ac1.firebaseapp.com",
    projectId: "studio-2419555289-92ac1",
    storageBucket: "studio-2419555289-92ac1.appspot.com",
    messagingSenderId: "1030188245249",
    appId: "1:1030188245249:web:99a86b5b036335d8a57b00",
    measurementId: "",
};
